name: paternproject
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'







dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_firebase_firestore: ^0.0.1
  get: ^4.6.5
  intl: ^0.18.0
  lottie: ^2.2.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter




flutter:

  
  
  
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
